server {
    client_max_body_size 101m;
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;
    location /api/ {
        resolver 127.0.0.11 valid=5s ipv6=off;
        set $backend http://backend:8000;
        proxy_pass $backend$request_uri;
        proxy_set_header Host $host;
        proxy_read_timeout 180s;
    }
    location / { try_files $uri $uri/ /index.html; }
}
