"""Build a portable Excel QA workbook using only Python's standard library."""
from pathlib import Path
from zipfile import ZipFile, ZIP_DEFLATED
from xml.sax.saxutils import escape
import csv
import xml.etree.ElementTree as ET

ROOT = Path(__file__).resolve().parent
P = 'http://localhost:5173/#/projects/12809bf1-825c-4e0d-997d-91a656b48e6e'
results = [
['ID','Journey / check','Status','Observed result / limits','Evidence','Retest'],
['J1','Create/select project','PASS','Created two isolated QA projects. New project immediately appears in switcher after fix. Existing four projects untouched.','20-project-switcher-after.png','Create another isolated project; verify list and switcher without reload.'],
['J2','Upload/process/inspect','PASS','597-byte TXT produced 1 chunk; text PDF produced 2 page chunks. Inspected exact content.','14-pdf-chunks.png','Upload sample-data/orchard-policy.txt; process; inspect first chunk.'],
['J3','Index and retrieval','PASS','Live OpenRouter embedding, pgvector index 1 ready; two retrieval calls returned policy text with cosine distance/provenance. Selected index survives reload and navigation.','19-retrieval-after.png','Select index 1; search What is the return window?; check 30-day evidence.'],
['J4','Configure/save pipeline','PASS','Saved Orchard policy QA v1 and v2, same index/top k=1, different answer instructions. Validation disables save without index.','35-pipeline-desktop-final.png','Open editor; inspect v1/v2; Test pipeline opens selected saved version.'],
['J5','Playground/answers/citations','PASS','Live answer states 30-day return window. Citation focuses actual supplied source. History opens saved outputs; chunk label now 1.','30-citation-verified-after.png','Open previous answer; activate S1 by keyboard; inspect focused source.'],
['J6','Evaluation dataset','PASS','Previewed/reviewed/imported two CSV questions with reference answers. Dataset automatically selected after import.','08-dataset-preview-before.png','Preview sample-data/reviewed-questions.csv; inspect both rows before import.'],
['J7','Two-version experiment','PASS','Live RAGAS 0.4.3 faithfulness, configured openai/gpt-5.6-luna. Four results completed.','25-experiment-desktop-after.png','Open saved experiment; inspect both immutable candidate versions.'],
['J8','Scores/answers/evidence/export','PASS','Faithfulness 1.0 for each answerable result (n=1/2 each); unsupported year abstained, metric unavailable. CSV downloaded through UI and parsed: four rows.','experiment-results.csv','Compare exported candidate/version/index/status/answer/score fields with UI.'],
['N1','Sidebar/breadcrumb/current page','PASS','Active navigation, project context and section labels verified. Mobile Escape fixed and focus returned to toggle.','17-documents-mobile-after.png','At 390px open menu then Escape; button should say Open navigation.'],
['N2','Refresh/direct links/back/forward','PASS','Saved experiment, pipeline and explicit index survive refresh. Back/forward restored index/settings routes.','37-project-return-selection.png','Visit index link, Settings, Back, Forward; inspect route and selection.'],
['N3','Project isolation/switching','PASS','Empty QA project showed no other project data. Returning restores saved Playground pipeline/version. UI isolation and isolated backend project-access regression suite passed.','21-empty-playground.png','Switch between the two QA projects on Playground.'],
['N4','Processing cancellation/retry','PASS','PDF v2 cancelled; v1 chunks remained inspectable; v3 retry succeeded.','15-processing-cancelled.png','Cancel a fresh processing version; inspect earlier successful version.'],
['N5','Index cancellation','PASS','Index v2 cancelled; ready v1 remained selected/searchable. No replacement index published.','18-index-cancellation-after.png','Start bounded index then cancel; retrieve against v1.'],
['N6','Experiment cancellation','PASS','Reached cancelled state. Both metrics skipped; one in-flight query retained latency/tokens/cost.','24-experiment-cancel-terminal.png','Inspect QA cancel check; confirm no pending items and retained in-flight output.'],
['N7','Validation/error/recovery','PASS','Missing upload rejected. Malformed PDF failed with actionable error. Offline Settings displayed Retry; restoring network and retry succeeded.','38-network-error.png','Temporarily set browser offline only; navigate Settings; restore network and Retry.'],
['N8','Mobile/keyboard/readability','PASS WITH LIMITS','390x844 and desktop inspected. No page overflow on measured experiment/editor views. Paired table ArrowRight moved scrollLeft to 40px. Scoped metadata and mobile targets improved; desktop Playground received the final visual focus.','26-experiment-mobile-after.png','Focus Paired comparison; ArrowRight; verify all candidate columns reachable.'],
['N9','Unsaved pipeline changes','PASS WITH LIMITS','Navigation raised Discard unsaved pipeline changes? Dismiss retained prompt draft; saved v2 afterward. Refresh beforeunload auto-accepted by CLI, so not manually verified.','05-pipeline-desktop-before.png','Change prompt; navigate; dismiss; verify draft; then explicitly discard.'],
['N10','Experiment form draft continuity','PASS','Name, dataset, both candidates and metrics survive navigation, reload and project switch; Reset draft clears only unsaved inputs.','51-draft-two-candidates-restored.png','Select dataset/two versions, navigate to editor and back; draft should persist after follow-up fix.'],
['N11','Rendering model Markdown','PASS','Stored live v1 emphasis renders correctly; citation opens source sidebar; automated tests cover lists/code and inert HTML.','65-desktop-bottom-composer.png','Test safe formatting with emphasis, lists, citations and malicious HTML.'],
['V1','Frontend regressions','PASS','36 tests across 9 files; lint/typecheck/production build passed. Includes citation sidebar, safe rendering and draft continuity.','../frontend/src/features/documents/IndexPanel.test.tsx','npm run test -- --run; npm run lint; npm run typecheck; npm run build in frontend.'],
['V2','Backend isolated regression','PASS / SKIP','146 passed, 1 skipped (opt-in standalone live embedding). PostgreSQL/pgvector migrations, failures, recovery, duplicate delivery, cancellation and access isolation covered.','','docker compose exec -T backend python -m pytest -q'],
['V3','Additional coverage','NOT RUN','Screen reader, all physical devices, exhaustive upload limits and real provider outage/worker-crash injection not performed. Isolated database/worker regression and bounded live relevancy/recall now performed.','','Run targeted isolated suites; never reset developer data.'],
]
ui = [
['ID','Priority','Surface','Finding','Status / change','Evidence','Follow-up prompt','Acceptance / recheck'],
['UI1','P2','Projects','New project missing from switcher','FIXED: creation callback refreshes shell project list.','20-project-switcher-after.png','Keep project listing and global switcher synchronized after future project mutations.','New project visible immediately without navigation.'],
['UI2','P2','Knowledge Base','Queued notices persisted after terminal state','FIXED: notices describe version creation and point to live history; applies to indexing and processing.','40-processing-status-after.png','Keep operation notices factual after status changes.','Failed/ready/cancelled histories never conflict with a current queued claim.'],
['UI3','P2','Playground','Chunk 0 vs Chunk 1 inconsistency','FIXED: display ordinal + 1; stored ordinal unchanged.','30-citation-verified-after.png','Use one-based chunk labels consistently in all user-facing evidence views.','First chunk labeled 1 in retrieval and Playground.'],
['UI4','P2','Mobile sidebar','Escape did not work from focused toggle','FIXED: Escape handler covers entire sidebar.','17-documents-mobile-after.png','Retain mobile navigation Escape and focus behavior.','Toggle and navigation descendants both close with Escape.'],
['UI5','P2','Knowledge Base navigation','Selected index lost on refresh/return','FIXED: explicit index URL and project-scoped restore; per-project route memory.','19-retrieval-after.png','Preserve selected ready index while keeping cross-project IDs rejected.','Reload/back/direct link restore selected ready index.'],
['UI6','P2','Project switching','Playground version lost switching projects','FIXED: switcher reuses only destination project saved route.','37-project-return-selection.png','Keep Playground and Knowledge Base selections scoped per project.','Switch away/back returns same version without leaking source data.'],
['UI7','P2','Experiment tables','Hidden right-side columns unclear on mobile','FIXED: scroll hint and focus targets on paired/history tables; visible focus.','26-experiment-mobile-after.png','Explore a mobile stacked comparison layout while preserving paired data.','All columns reachable by touch and keyboard; no page overflow.'],
['UI8','P2','Evaluation costs','Relevancy cost caveat displayed for faithfulness-only run','FIXED: caveat conditional on response relevancy metric.','25-experiment-desktop-after.png','Show metric-specific cost limitations only when relevant.','Faithfulness-only UI has no relevancy-embedding caveat.'],
['UI9','P2','Answers','Literal Markdown emphasis','FIXED: inert React formatting for emphasis, lists and code; citations remain verified buttons.','65-desktop-bottom-composer.png','Implement safe answer formatting without executing HTML or converting unverified references into citations. Preserve original saved answer text.','Bold/list/code display correctly; S1 remains focusable; HTML remains inert.'],
['UI10','P2','Experiment creation','Unsaved selections lost navigating away','FIXED: project-scoped tab draft; validated identifiers; explicit Reset draft.','51-draft-two-candidates-restored.png','Preserve experiment draft per project across editor visits and refresh; add clear reset. Store identifiers/settings, not uploaded file bodies or secrets.','Dataset, candidates, metrics and name restored; stale versions validated.'],
['UI11','P2','Empty Playground','No direct next-action link to ingestion','FIXED: upload and index action opens the project upload form.','49-empty-action-upload-destination.png','Add a clear Knowledge Base link to no-ready-index Playground state and focus it appropriately.','Empty-state user reaches document upload in one action.'],
['UI12','P3','Metadata and mobile controls','Dense metadata; some controls under 44px high','FIXED scoped issues: readable metadata and 44px mobile controls; full WCAG audit remains outside this verification.','53-editor-mobile-final.png','Improve small metadata readability and mobile targets while preserving compact desktop layout; test 200% zoom and 390px viewport.','No clipping; target size and contrast checked quantitatively.'],
]
pointers = [
['ID','Area','Observed / next check','Priority','Prompt to implement or investigate','Retest recipe','Budget / boundary'],
['R1','RAG grounding','Return-window question answered with exact policy evidence.','Maintain','Verify citations reference only evidence actually sent. Add cases where a source is relevant but does not support the claim.','Ask How long do I have to return an unused sensor?; compare answer with S1 and 30-day text.','Reuse index 1; one question per variant.'],
['R2','RAG abstention','Both candidates abstained on founding year.','Maintain','Extend reviewed unanswerable questions without inventing references; inspect explicit insufficient-evidence outputs.','Ask What year was Orchard founded?; expect abstention and no invented year.','Two small extra questions max for live check.'],
['R3','Retrieval coverage','Only one policy chunk in measured index; does not measure ranking quality.','P2','Build a human-reviewed multi-document dataset with distractors and source labels before tuning top_k. Compare on identical index versions.','Include relevant/irrelevant chunks; inspect rank, distance and evidence inclusion.','Use isolated project; approve larger live budget before broad sweeps.'],
['R4','Pipeline prompt comparison','v1 concise default; v2 one plain-text sentence, explicit abstention.','Maintain','Compare prompt variants using the same dataset/index/models. Show prompt differences beside candidates.','Open immutable configuration; verify v1/v2 prompt changes and same index/top_k=1.','No inference of winner from this two-question sample.'],
['E1','Metric semantics','Faithfulness 1.0 each, scored n=1/2; abstention unavailable.','Maintain','Retain all failed/skipped/unavailable counts. Explain that faithfulness is support in context, not overall accuracy.','Compare mean with per-question status; abstentions must never become zero or fake scores.','Reuse persisted experiment; no calls needed.'],
['E2','Other metrics','LIVE VERIFIED: two-row v2 experiment succeeded. Relevancy approximately 0.9 on answerable row (1/2); abstention unavailable. Context recall 1.0 (2/2). Missing-reference rules covered in regression.','P2','Run bounded live checks of response relevancy and context recall behind the evaluator interface, including missing reference data.','One answerable row plus one missing-reference row; unavailable context recall for missing reference.','Small opt-in run; separate from deterministic tests.'],
['E3','Reproducibility/export','CSV has four rows and selected metric/status fields; source evidence inspected separately in UI.','P2','Add a versioned evidence-inclusive JSON export if reviewers need a self-contained offline record; retain immutable snapshots.','Round-trip candidate/version/index/question/output/evidence/evaluator metadata without changing historical records.','Read-only export; no provider calls.'],
['E4','Costs','Reported measured experiment generation $0.000490 + evaluation $0.000997; embeddings excluded.','Maintain','Keep indexing/query/evaluation costs separate; label partial sums and their pricing basis. Unknown is not zero.','Check token counts and cost columns in CSV against UI; inspect cancellation in-flight cost.','Do not represent known subtotal as complete spend.'],
['E5','Robustness','Isolated PostgreSQL/worker regression passed: duplicate delivery, stale recovery, broker/provider failure and cancellation. Real provider outage was not deliberately induced.','P2','Run isolated PostgreSQL/worker regression coverage for duplicate delivery, cancellation, stale jobs and provider failures.','Never publish incomplete index; terminal jobs must not remain running; preserve prior results.','Deterministic provider stubs only in automated tests, never represented as live verification.'],
['E6','Validation and scope','Two rows insufficient for recommendations or quality guarantees.','P2','Prepare a larger held-out human-reviewed evaluation set before recommending settings. Include source provenance and aggregation rules.','Compare variants on identical reviewed data; report sample counts and uncertainty.','Plan live costs before expanding dataset.'],
]
summary=[['Item','Result'],['Application','http://localhost:5173'],['QA project',P],['Pipeline',P+'/pipelines/87543365-224d-4e72-a4cd-6c898b7def8d'],['Experiment',P+'/experiments/5c3012f6-2da0-4ca4-a4e1-e6984db5fa64'],['Scope','All eight core journeys passed; identified UI issues fixed; unperformed checks and optional extensions listed explicitly. No core journey blocked.'],['Data safety','Two isolated QA projects created. Existing projects/documents untouched. No credentials in artifacts. No mock browser responses.'],['Models','Configured OpenRouter embedding model openai/text-embedding-3-small; chat/evaluator openai/gpt-5.6-luna.'],['Live execution','One 1-chunk completed index, one cancelled replacement; two retrieval probes; one Playground answer; four experiment queries + two faithfulness metric results; cancellation retained one additional in-flight query.'],['Costs','Known completed-experiment subtotal $0.001487 excluding embeddings; not total session spend.'],['Tests','Frontend 36 passed; lint/typecheck/build passed. Backend 146 passed / 1 opt-in skipped. Final browser regression details in Tests tab and logs.'],['Screenshots',str(len(list(ROOT.glob('*.png'))))+' PNGs retained. Earlier captures are before/intermediate evidence; use latest desktop final screenshots for delivered UI.'],['Limitations','Small sample; no general quality guarantee. See Tests and RAG Evaluation tabs for unperformed checks.']]
ui.extend([
['UI13','P1','Playground entry','Direct entry and editor entry lost selection during fast navigation','FIXED: immediate project-scoped route memory, synchronized query parameters, preserved ready-index/top-k and exact saved editor version.','73-desktop-settings-final.png','Keep every Playground entry on the same layout and saved configuration.','Open Playground from editor; navigate away before version fetch completes; return from sidebar; reload. Same version.'],
['UI14','P1','Desktop chat layout','Dense settings, results and metadata mixed into chat; composer floated mid-page','FIXED: bottom-aligned composer, independently scrolling messages, optional right-side settings/history/answer inspector.','87-sidebar-final-desktop.png','Keep the composer at the viewport bottom as messages and evidence grow.','At 1280x800 and 1440x1000, input and inspector end 20px above viewport bottom; no document scroll.'],
['UI15','P2','History and evidence','Full-width history consumed page; citations and run details interrupted conversation','FIXED: compact scrollable history sidebar; citations open source sidebar; run details tab; close/Escape returns focus.','71-desktop-source-inspector-final.png','Keep answer metadata and source documents in the sidebar.','Open S1, switch Run details, close with Escape; chat and input stay in place.'],
['UI16','P2','Terminology','Retrieval search vs answer generation unclear','FIXED: Playground separates Retrieval test and Pipeline test; actual pipeline names and editable settings appear in the sidebar.','86-live-retrieval-sidebar.png','Keep retrieval-only search distinct from RAG answer generation.','Retrieval test returns ranked text only; Pipeline test generates an answer with citations using current settings.'],
])
results.extend([
['N12','Desktop chat / side inspector','PASS','Live warranty answer: manufacturing defects for 12 months, accidental damage excluded. S1 focuses supplied source; source and run details in sidebar; bottom composer remains visible.','87-sidebar-final-desktop.png','Open S1, Run details, history, settings; verify message box stays at bottom.'],
['N13','Consistent entry and exact saved version','PASS','Route race reproduced by automated fast navigation and fixed; direct index settings survive reload; Edit pipeline carries selected immutable version.','73-desktop-settings-final.png','From saved v1 while v2 exists: Open Playground, sidebar navigation, refresh, Edit pipeline; verify v1.'],
['E2','Additional live metrics','PASS','Two-row v2 run: relevance scored 1/2, abstention unavailable; context recall scored 2/2. Exported results through real UI.','other-metrics-results.csv','Inspect QA follow-up remaining metrics saved experiment.'],
])
summary.append(['Additional live run','Warranty question: 2.53s total, generation cost $0.000118 excluding retrieval embeddings; 461 tokens. Real configured provider; no substituted results.'])
summary.append(['Design references','Carbon AI Chat prompt-line bottom placement; PatternFly Chatbot header/content/footer structure. Existing React/CSS architecture retained; no UI framework/dependency added.'])
results.extend([
['N14','Editable Playground settings','PASS','Live draft used Top k 2 and a one-sentence prompt with 128 output tokens. Answer correctly cited the 12-month manufacturing-defect warranty. Saved versions remained unchanged.','85-live-draft-details.png','Change prompt/Top k/token budget, run, inspect exact settings; explicitly save a new version only when intended.'],
['N15','Desktop sidebar alignment','PASS','1440x1000 and 1280x800: sidebar spans workspace height, fixed header/save footer, independent settings scroll; composer stays at bottom. Keyboard reaches lower settings.','87-sidebar-final-desktop.png','Tab through prompt/model/budget; scroll settings; open sources and details; check sidebar bottom remains aligned with input.'],
])
ui.extend([
['UI17','P1','Interactive testing','Playground settings were not editable during testing','FIXED: real retrieval-only testing and validated pipeline draft execution; immutable snapshots and explicit version saving.','85-live-draft-details.png','Let users test actual parameter changes without overwriting saved pipelines.','Browser regression confirms settings reach the engine, saved versions stay immutable, and reset restores values.'],
['UI18','P2','Right sidebar layout','Sidebar began below the workspace header; large gaps and scrolling hid actions','FIXED: full workspace height, consistent field spacing, fixed heading and save area, normal-weight prompt text.','87-sidebar-final-desktop.png','Keep the sidebar restrained and aligned with the chat workspace.','Compare 80-sidebar-before.png with 87-sidebar-final-desktop.png; inspect 1280px and scrolled settings.'],
])
summary.append(['Latest desktop pass','Sidebar refined at 1440x1000 and 1280x800. Live retrieval and one bounded pipeline draft both passed; draft generation cost $0.000116 excluding embeddings, 455 tokens, 2.63s.'])
results.append(['V4','Final browser regression','PASS / SKIP','9 passed; missing-credential scenario skipped in the configured-provider fixture stack. Includes editable Playground, immutable save/reset, ingestion, pipeline and experiment journeys.','playwright-delivery-final.log','Use isolated Compose fixture services; do not reset developer data.'])
export=list(csv.reader((ROOT/'experiment-results.csv').open()))
shots=[['Screenshot','Purpose / note','Link']]
for p in sorted(ROOT.glob('*.png')):
    note=p.stem.replace('-', ' ')
    if p.name.startswith(('28-','29-')): note='Exploratory Playground history view; use 30 for confirmed citation result.'
    shots.append([p.name,note,p.name])
sheets=[('Summary',summary),('Tests',results),('UI Improvements',ui),('RAG Evaluation',pointers),('Exported Results',export),('Other Metrics Export',list(csv.reader((ROOT/'other-metrics-results.csv').open()))),('Screenshots',shots)]
NS='http://schemas.openxmlformats.org/spreadsheetml/2006/main'
REL='http://schemas.openxmlformats.org/officeDocument/2006/relationships'
def col(n):
    s=''
    while n: n,r=divmod(n-1,26); s=chr(65+r)+s
    return s

def worksheet(rows):
    out=[f'<worksheet xmlns="{NS}" xmlns:r="{REL}"><sheetViews><sheetView workbookViewId="0"><pane ySplit="1" topLeftCell="A2" activePane="bottomLeft" state="frozen"/></sheetView></sheetViews><cols>']
    for i in range(1,len(rows[0])+1):
        width=18 if i==1 else 42 if i<4 else 66
        out.append(f'<col min="{i}" max="{i}" width="{width}" customWidth="1"/>')
    out.append('</cols><sheetData>')
    links=[]
    for r,row in enumerate(rows,1):
        out.append(f'<row r="{r}" ht="{32 if r==1 else 82}" customHeight="1">')
        for c,value in enumerate(row,1):
            value=str(value);ref=f'{col(c)}{r}';style=1 if r==1 else 2+(r%2)
            if r>1 and ((ROOT/value).is_file() if len(value)<240 and '\n' not in value else False) and value.endswith(('.png','.csv','.tsx')):
                links.append((ref,value));style=4
            elif r>1 and value.startswith('http'):
                links.append((ref,value));style=4
            out.append(f'<c r="{ref}" t="inlineStr" s="{style}"><is><t xml:space="preserve">{escape(value)}</t></is></c>')
        out.append('</row>')
    out.append(f'</sheetData><autoFilter ref="A1:{col(len(rows[0]))}{len(rows)}"/>')
    if links: out.append('<hyperlinks>'+''.join(f'<hyperlink ref="{ref}" r:id="rId{i}"/>' for i,(ref,_) in enumerate(links,1))+'</hyperlinks>')
    out.append('</worksheet>')
    relationships='<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">'+''.join(f'<Relationship Id="rId{i}" Type="{REL}/hyperlink" Target="{escape(target, {chr(34): "&quot;"})}" TargetMode="External"/>' for i,(_,target) in enumerate(links,1))+'</Relationships>'
    return ''.join(out),relationships
styles=f'''<styleSheet xmlns="{NS}"><fonts count="3"><font><sz val="11"/><name val="Calibri"/></font><font><b/><color rgb="FFFFFFFF"/><sz val="11"/><name val="Calibri"/></font><font><u/><color rgb="FF5342A0"/><sz val="11"/><name val="Calibri"/></font></fonts><fills count="4"><fill><patternFill patternType="none"/></fill><fill><patternFill patternType="gray125"/></fill><fill><patternFill patternType="solid"><fgColor rgb="FF252B36"/></patternFill></fill><fill><patternFill patternType="solid"><fgColor rgb="FFF0EEF8"/></patternFill></fill></fills><borders count="1"><border/></borders><cellStyleXfs count="1"><xf numFmtId="0" fontId="0" fillId="0" borderId="0"/></cellStyleXfs><cellXfs count="5"><xf numFmtId="0" fontId="0" fillId="0" borderId="0" xfId="0"/><xf numFmtId="0" fontId="1" fillId="2" borderId="0" xfId="0" applyAlignment="1"><alignment vertical="center" wrapText="1"/></xf><xf numFmtId="0" fontId="0" fillId="0" borderId="0" xfId="0" applyAlignment="1"><alignment vertical="top" wrapText="1"/></xf><xf numFmtId="0" fontId="0" fillId="3" borderId="0" xfId="0" applyAlignment="1"><alignment vertical="top" wrapText="1"/></xf><xf numFmtId="0" fontId="2" fillId="0" borderId="0" xfId="0" applyAlignment="1"><alignment vertical="top" wrapText="1"/></xf></cellXfs><cellStyles count="1"><cellStyle name="Normal" xfId="0" builtinId="0"/></cellStyles></styleSheet>'''
with ZipFile(ROOT/'qa-report.xlsx','w',ZIP_DEFLATED) as z:
    types='<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/><Override PartName="/xl/styles.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.styles+xml"/>'+''.join(f'<Override PartName="/xl/worksheets/sheet{i}.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/>' for i in range(1,len(sheets)+1))+'</Types>'
    z.writestr('[Content_Types].xml',types)
    z.writestr('_rels/.rels',f'<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="{REL}/officeDocument" Target="xl/workbook.xml"/></Relationships>')
    z.writestr('xl/workbook.xml',f'<workbook xmlns="{NS}" xmlns:r="{REL}"><sheets>'+''.join(f'<sheet name="{name}" sheetId="{i}" r:id="rId{i}"/>' for i,(name,_) in enumerate(sheets,1))+'</sheets></workbook>')
    z.writestr('xl/_rels/workbook.xml.rels','<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">'+''.join(f'<Relationship Id="rId{i}" Type="{REL}/worksheet" Target="worksheets/sheet{i}.xml"/>' for i in range(1,len(sheets)+1))+f'<Relationship Id="rId{len(sheets)+1}" Type="{REL}/styles" Target="styles.xml"/></Relationships>')
    z.writestr('xl/styles.xml',styles)
    for i,(_,rows) in enumerate(sheets,1):
        data,rels=worksheet(rows);z.writestr(f'xl/worksheets/sheet{i}.xml',data);z.writestr(f'xl/worksheets/_rels/sheet{i}.xml.rels',rels)
with ZipFile(ROOT/'qa-report.xlsx') as z:
    assert z.testzip() is None
    for name in z.namelist(): ET.fromstring(z.read(name))
print('Validated workbook:',len(sheets),'tabs;',len(results)-1,'test rows;',len(shots)-1,'screenshots;',len(export)-1,'export rows.')
