import { test, expect } from '@playwright/test';

test('pipeline create configure save reopen run evidence and immutable versions', async ({ page, request }) => {
  test.skip(process.env.E2E_EMBEDDING_FIXTURE !== '1', 'Requires isolated deterministic providers.');
  test.setTimeout(120000);
  page.setDefaultTimeout(15000);
  const project = await (await request.post('/api/projects', { data: { name: `Pipeline ${Date.now()}` } })).json() as { id: string };
  await page.goto(`/#/projects/${project.id}`);
  await page.getByRole('button', { name: 'Add document', exact: true }).click();
  await page.getByLabel('PDF or UTF-8 TXT').setInputFiles({ name: 'orchard.txt', mimeType: 'text/plain', buffer: Buffer.from('The orchard grows apples. The harvest begins in September.') });
  await page.getByRole('button', { name: 'Upload document', exact: true }).click();
  await page.getByRole('button', { name: 'Start processing', exact: true }).click();
  await expect(page.getByRole('button', { name: 'Inspect 1 chunks' })).toBeVisible({ timeout: 30000 });
  await page.getByRole('button', { name: 'Indexes', exact: true }).click();
  await page.getByRole('button', { name: 'Index documents' }).click();
  await expect(page.getByRole('button', { name: 'Use index 1' })).toBeVisible({ timeout: 30000 });
  await page.getByRole('link', { name: 'Pipelines', exact: true }).click();
  await page.getByRole('link', { name: 'New pipeline', exact: true }).click();
  await page.getByLabel('Pipeline name', { exact: true }).fill('Orchard answers');
  const retriever = page.locator('.react-flow__node[data-id="retriever"]');
  const box = (await retriever.boundingBox())!;
  await page.mouse.move(box.x + 15, box.y + 15);
  await page.mouse.down();
  await page.mouse.move(box.x + 35, box.y + 45, { steps: 8 });
  await page.mouse.up();
  await page.getByLabel('Ready index', { exact: true }).selectOption({ label: 'Index 1 · 1 chunks' });
  await page.getByLabel('Top k', { exact: true }).fill('3');
  await page.getByLabel('Selected node').selectOption('prompt');
  await page.getByLabel('Answer instructions').fill('Answer concisely. Question: {question} Context: {context}');
  await page.getByRole('button', { name: 'Save version', exact: true }).click();
  await expect(page.getByText('Saved version 1', { exact: true })).toBeVisible();
  await page.reload();
  await expect(page.getByLabel('Pipeline name', { exact: true })).toHaveValue('Orchard answers');
  await expect(page.getByText('Saved version 1', { exact: true })).toBeVisible();
  await page.getByLabel('Selected node').selectOption('prompt');
  await expect(page.getByLabel('Answer instructions')).toHaveValue('Answer concisely. Question: {question} Context: {context}');
  await page.getByRole('button', { name: 'Test pipeline', exact: true }).click();
  await page.getByLabel('Question', { exact: true }).fill('What does the orchard grow?');
  await page.getByRole('button', { name: 'Ask question', exact: true }).click();
  const result = page.getByRole('region', { name: 'Query result' });
  await expect(result.getByText('The orchard grows apples.', { exact: true })).toBeVisible({ timeout: 30000 });
  await result.getByRole('button', { name: '[S1]', exact: true }).click();
  await expect(page.locator('#evidence-S1')).toBeFocused();
  await expect(result.getByText(/Pipeline version 1/)).toBeVisible();
  await page.getByRole('link', { name: 'Edit pipeline', exact: true }).click();
  await page.getByLabel('Selected node').selectOption('retriever');
  await page.getByLabel('Top k', { exact: true }).fill('1');
  await expect(page.getByRole('button', { name: 'Test pipeline', exact: true })).toBeDisabled();
  await page.getByRole('button', { name: 'Save version', exact: true }).click();
  await expect(page.getByText('Saved version 2', { exact: true })).toBeVisible();
  await page.getByLabel('Saved version', { exact: true }).selectOption({ label: 'Version 1' });
  await page.getByLabel('Selected node').selectOption('retriever');
  await expect(page.getByLabel('Top k', { exact: true })).toHaveValue('3');
  await page.setViewportSize({ width: 1600, height: 1100 });
  await page.getByLabel('Selected node').selectOption('question');
  await page.getByLabel('Selected node').selectOption('retriever');
  await expect(page.locator('.react-flow__node[data-id="retriever"] .workflow-selected')).toBeVisible();
  const canvas = page.locator('.pipeline-canvas');
  const canvasBefore = (await canvas.boundingBox())!;
  expect(canvasBefore.height).toBeGreaterThan(660);
  await page.getByRole('button', { name: 'Hide settings', exact: true }).click();
  await expect(page.getByLabel('Selected node')).toBeHidden();
  expect((await canvas.boundingBox())!.width).toBeGreaterThan(canvasBefore.width + 250);
  await page.getByRole('button', { name: 'Node settings', exact: true }).click();
  await expect(page.getByLabel('Selected node')).toBeVisible();
  await page.screenshot({ path: 'test-results/pipeline-desktop.png' });
  await page.setViewportSize({ width: 390, height: 844 });
  await page.getByLabel('Selected node').selectOption('question');
  await page.getByLabel('Selected node').selectOption('retriever');
  await page.locator('.pipeline-editor').screenshot({ path: 'test-results/pipeline-mobile.png' });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.getByRole('button', { name: 'Duplicate pipeline', exact: true }).click();
  await expect(page.getByLabel('Pipeline name', { exact: true })).toHaveValue('Orchard answers (copy)');
  await page.getByLabel('Selected node').selectOption('answer');
  await page.getByRole('button', { name: 'Delete selected node', exact: true }).click();
  await expect(page.getByRole('button', { name: 'Save version', exact: true })).toBeDisabled();
  await expect(page.getByRole('region', { name: 'Graph validation' })).toContainText('Require exactly one');
  await page.getByRole('button', { name: 'Nodes', exact: true }).click();
  await page.getByRole('button', { name: 'Add Answer', exact: true }).click();
  await expect(page.getByRole('region', { name: 'Graph validation' })).toContainText('Connect Question');
  await page.getByRole('button', { name: 'Discard changes', exact: true }).click();
});
