import { test, expect } from '@playwright/test';

test('single-turn answers, evidence, insufficient evidence and persisted history', async ({ page, request }) => {
  test.skip(process.env.E2E_EMBEDDING_FIXTURE !== '1', 'Requires isolated deterministic providers.');
  test.setTimeout(90000);
  const project = await (await request.post('/api/projects', { data: { name: `Playground ${Date.now()}` } })).json() as { id: string };
  await page.goto(`/#/projects/${project.id}`);
  await page.getByRole('button', { name: 'Add document', exact: true }).click();
  await page.getByLabel('PDF or UTF-8 TXT').setInputFiles({ name: 'orchard.txt', mimeType: 'text/plain', buffer: Buffer.from('The orchard grows apples. The harvest begins in September.') });
  await page.getByRole('button', { name: 'Upload document', exact: true }).click();
  await page.getByRole('button', { name: 'Start processing', exact: true }).click();
  await expect(page.getByRole('button', { name: 'Inspect 1 chunks' })).toBeVisible({ timeout: 30000 });
  await page.getByRole('button', { name: 'Indexes', exact: true }).click();
  await page.getByRole('button', { name: 'Index documents' }).click();
  await expect(page.getByRole('button', { name: 'Use index 1' })).toBeVisible({ timeout: 30000 });
  await page.getByRole('link', { name: 'Playground', exact: true }).click();
  await page.getByLabel('Ready index').selectOption({ label: 'Index 1 · 1 chunks' });
  await page.getByLabel('Question', { exact: true }).fill('What does the orchard grow?');
  await page.getByLabel('Top k', { exact: true }).fill('3');
  await page.getByRole('button', { name: 'Ask question', exact: true }).click();
  const result = page.getByRole('region', { name: 'Query result' });
  await expect(result.getByText('The orchard grows apples.', { exact: true })).toBeVisible();
  await result.getByRole('button', { name: '[S1]', exact: true }).click();
  await expect(page.locator('#evidence-S1')).toBeFocused();
  await expect(result.getByText('The orchard grows apples. The harvest begins in September.', { exact: true })).toBeVisible();
  await page.setViewportSize({ width: 1440, height: 1000 });
  await result.screenshot({ path: 'test-results/playground-desktop.png' });
  await page.setViewportSize({ width: 390, height: 844 });
  await result.screenshot({ path: 'test-results/playground-mobile.png' });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.getByLabel('Question', { exact: true }).fill('What is the launch code?');
  await page.getByRole('button', { name: 'Ask question', exact: true }).click();
  await expect(result.getByRole('heading', { name: 'Insufficient evidence', exact: true })).toBeVisible();
  await page.reload();
  await page.getByText('Previous runs', { exact: true }).click();
  await page.getByRole('button', { name: 'What does the orchard grow?', exact: true }).click();
  await expect(result.getByText('The orchard grows apples.', { exact: true })).toBeVisible();
  await expect(result.getByText(/Saved index 1 · Top k 3/)).toBeVisible();
});
